### ISSUE TITLE
Documentation for local test setup

### ISSUE THREAD

**Issue by AOphagen** [FreifunkMD/Meshviewer#22]
Working with this code, I want to be able to set it up locally for the most basic smoke tests before rolling out any changes.

I'd like the `README.md` to contain a how-to for setting the code up in a development environment locally.
I'd also be happy with another solution, like `mkdocs` for developers, but that is not necessary, really.

I'll start to document any solution for a local set-up I come up with on my own, but even so, help would be greatly appreciated.

**Comment by penguineer** [comment]
Wir nutzen folgendes docker-compose file:

```yaml
version: '3'

services:
  meshviewer:
    image: ffmd/meshviewer-server:latest
    container_name: ffmd_meshviewer_server
    restart: unless-stopped
    depends_on:
      - ffmd_yanic
    ports:
      - 8010:80
    environment:
      - MeshviewerRepo = "https://github.com/FreifunkMD/Meshviewer --branch ffmd"
      - LoopHookCMD = "wget http://gw01.babel.md.freifunk.net:8080/data/meshviewer.json -O /var/www/html/data/meshviewer.json"
  ffmd_yanic:
    image: ffmd/yanic:latest
    network_mode: "host"
    restart: unless-stopped
    container_name: ffmd_yanic
    volumes:
            - /opt/yanic/config.toml:/etc/yanic.conf
```
